FROM node

# 修改时区

# 安装依赖
#RUN apt-get update && \
# apt-get install -y --no-install-recommends \
# curl

#安装 Hexo
RUN npm install -g hexo-cli

VOLUME /blog

#RUN hexo init /blog \
#  && cd /blog \
#  && npm install
ADD init.tar.gz /blog
ADD themes.tar.gz /blog/themes/yilia
COPY posts /blog/source/_posts
COPY resource /blog/resource
COPY _config.yml /blog/

RUN cd /blog \
  && hexo generate \
  && mv /blog/public/ /usr/share/nginx/html/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
