FROM node

# 修改时区

# 安装依赖
#RUN apt-get update && \
# apt-get install -y --no-install-recommends \
# curl

#安装 Hexo
RUN npm install -g hexo-cli

VOLUME /blog

RUN hexo init /blog \
  && cd /blog \
  && npm install

COPY posts /blog/source/_posts
COPY resource /blog/resource
COPY _config.yml /blog/

RUN cd /blog \
  && hexo generate \
  && cp public /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
